### ISSUE TITLE
大佬,我的运行出错,请看下

### ISSUE THREAD

**Issue by UTSOURCE** [leeyiding/get_CCB#1]
![image](https://user-images.githubusercontent.com/14830459/117119585-e01b1a80-adc4-11eb-90a6-04d2289f94bc.png)

**Comment by UTSOURCE** [comment]
是不是类型错了啊,我py不咋会

**Comment by leeyiding** [comment]
应该是接口偶发性报错了，重新运行一两遍脚本看看正常不？等我有时间修改一下逻辑

**Comment by UTSOURCE** [comment]
@leeyiding 不行,我等你更新吧

**Comment by tarianwei** [comment]
我和楼主的错误差不多：
Traceback (most recent call last):
  File "/home/script/CCB/main.py", line 307, in <module>
    user.main()
  File "/home/script/CCB/main.py", line 293, in main
    self.mothersDayTask()
  File "/home/script/CCB/main.py", line 274, in mothersDayTask
    friendName = userLaunchInfo['data']['nickname']
TypeError: string indices must be integers

**Comment by piaoyun** [comment]
开始做任务3【去赚鼓励金】
任务已完成
领取50.00建设值成功

开始做任务4【每天邀请3位好友建设城市】
助力逻辑未知
已全部领取奖励

开始做任务5【领取“1分钱骑行”优惠】
任务已完成
领取50.00建设值成功

开始做任务6【阅读一条财富资讯】
任务已完成
领取50.00建设值成功

开始做任务7【浏览金选产品】
任务已完成
领取成功

开始做任务8【领取“1分钱骑行”优惠】
Traceback (most recent call last):
  File "main.py", line 305, in <module>
    user.main()
  File "main.py", line 285, in main
    self.doTask()
  File "main.py", line 116, in doTask
    print(doTaskResult['message'])
TypeError: 'bool' object is not subscriptable

**Comment by leeyiding** [comment]
@piaoyun @UTSOURCE 两位的问题大概率是Cookie中的`XSRF-TOKEN`已失效，导致活动接口没有返回json数据，请各位重新更新Cookie后重试一下

**Comment by UTSOURCE** [comment]
![image](https://user-images.githubusercontent.com/14830459/117233676-31271f00-ae56-11eb-8eae-04dd0379a914.png)

是设置得这个吗?
但是提示我这个

![image](https://user-images.githubusercontent.com/14830459/117233707-3b491d80-ae56-11eb-9bbe-f560848d3c1d.png)

**Comment by leeyiding** [comment]
> ![image](https://user-images.githubusercontent.com/14830459/117233676-31271f00-ae56-11eb-8eae-04dd0379a914.png)
> 
> 是设置得这个吗?
> 但是提示我这个
> 
> ![image](https://user-images.githubusercontent.com/14830459/117233707-3b491d80-ae56-11eb-9bbe-f560848d3c1d.png)

在下面的Request Headersh中的cookie里截取`XSRF-TOKEN`和`__session`参数

**Comment by UTSOURCE** [comment]
@leeyiding 好了,已跑起来了,**谢谢!!!**

**Comment by Masteryi999** [comment]
能请教下定时任务怎么操作吗？可以跑python3 keepAlive.py 不知道定时怎么操作了

**Comment by UTSOURCE** [comment]
好像是 
crontab -e
添加
0 */3 * * * cd /脚本路径/ && python3 keepAlive.py 
然后保存,重启定时任务,
不知道对不

**Comment by Masteryi999** [comment]
> 好像是
> crontab -e
> 添加
> 0 */3 * * * cd /脚本路径/ && python3 keepAlive.py
> 然后保存,重启定时任务,
> 不知道对不

好的 感谢 我去试试

**Comment by Matear890** [comment]
[root@VM_0_11_centos get_CCB]# python3 main.py
脚本执行开始时间2021-05-08 23:40:17
Traceback (most recent call last):
  File "main.py", line 546, in <module>
    config = readConfig(configPath)
  File "main.py", line 539, in readConfig
    config = json.load(fp)
  File "/usr/local/sbin/python-3.7/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/sbin/python-3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/sbin/python-3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/sbin/python-3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 3 column 9 (char 26)

**Comment by leeyiding** [comment]
@Matear890 校验一下你的配置文件是否符合json格式
https://www.bejson.com/json/format/

**Comment by xukf2000** [comment]
大佬，顺便问下，互助吗我都填上去了，为什么3次的互助任务一次也没点上，是分别写，还是写在一个括号里
![image](https://user-images.githubusercontent.com/34463908/117562266-2b3c7280-b0d0-11eb-82b0-779b4011330f.png)

**Comment by leeyiding** [comment]
> 大佬，顺便问下，互助吗我都填上去了，为什么3次的互助任务一次也没点上，是分别写，还是写在一个括号里
> ![image](https://user-images.githubusercontent.com/34463908/117562266-2b3c7280-b0d0-11eb-82b0-779b4011330f.png)

同类互助吗统一填写在中括号里，以逗号分隔

**Comment by leeyiding** [comment]
> 全部放到一个里了，但是好像更新了代码，从云端直接给我安排了12个助力，自己还是没点上

估计主会场的助力次数每日也有上限，你的助力码已经提交到助力池了，等待别人帮你助力吧
