### ISSUE TITLE
cookie 包活 失败了

### ISSUE THREAD

**Issue by hjwpmnryo** [leeyiding/get_CCB#16]
Traceback (most recent call last):
  File "/mnt/mmcblk1p3/myid/mypython/get_CCB/keepAlive.py", line 71, in <module>
    result = getUserInfo(config['cookie'][i])
  File "/mnt/mmcblk1p3/myid/mypython/get_CCB/keepAlive.py", line 16, in getUserInfo
    return r.json()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by huaduxu** [comment]
兄弟，你黑号了
